version: '2'
services:
  insurance-app:
    image: insurance
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://insurance-postgresql:5432/insurance
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8083:8083
  insurance-postgresql:
    extends:
      file: postgresql.yml
      service: insurance-postgresql
